spring:
  application:
    name: demo
  datasource:
    url: jdbc:mysql://localhost:3306/fooddb?createDatabaseIfNotExist=true
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp

  sql:
    init:
      mode: always

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    defer-datasource-initialization: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect